### PR TITLE
Move Vcc.ini to user's Document folder.

### PR DESCRIPTION
**Pull request by jimrye**
Moved 'Vcc.ini' to user's Document folder so configuration changes will save and load properly without admin rights. Addresses issue #3 .

### CODE REVIEW

**Comment by BGPierce** [comment]
Jim, the one thing I see that may be a problem. Currently (this may change eventually) we are trying to keep compatibility as far back as Windows XP. So far we have been successful (It may even run on Win98, not sure).
In your patch, you specify "%HOMEPATH%\Documents\VCC", which is fine for Win7 and up. Win98-Win Vista uses "My Documents", which would conflict with your pathname. If I'm not mistaken (and I may be), using "{userdocs}\VCC" instead of "%HOMEPATH%\Documents\VCC" will expand to the user's Documents folder regardless of name. This is used by my installer script which seems to properly install the VCC manual in the proper folder regardless of OS.

Does this also address the writing of the config.ini during changes made after VCC is running (i.e. changing disks, changing config settings, etc)?

Also, hang on to this patch as I have another patch in the wings and they may conflict after that patch is made. I need to check out the other patch first as it's an age old bug that needs addressing.

Please keep a watch for the change and resubmit your pull request.

**Comment by jimrye** [comment]
Ok, I’ll look into using {userdocs} instead. I found another problem with it anyway. Closed pull request. Working on it…

Jim



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CoCo3-org** [comment]
Ahhh ... here is where I meant to leave a comment.  Sorry on issues! 

The accepted answer and the comments to it shed light on this issue ... 
https://stackoverflow.com/questions/5920853/how-to-open-a-folder-in-appdata-with-c

**Comment by jimrye** [comment]
I think I have this working. The AppData folder makes more sense anyway. Let me know when you’re ready for another pull request.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BGPierce** [comment]
Anytime. I think we have the other patch stable, so make sure you get a clean pull before patching.


-----Original Message-----

**Pull request closed without merging**
