### PR TITLE
Update tcc1014graphics.c

### PR DESCRIPTION
**Pull request by jimrye**
Changed artifact colors to more resemble those of the Coco 3.

### CODE REVIEW

**Comment by BGPierce** [comment]
I will give this a test run later and check it out

**Comment by jimrye** [comment]
Great, thanks! It's a pretty simple tweak, but I think its an improvement.

**Comment by BGPierce** [comment]
The patch seems to do the job, but the red/blue seem to be reversed.
BTW, what name can I give credit to this patch?

**Comment by jimrye** [comment]
Hi Bill,

My name’s James Rye. I thought it might be wrong, but I just checked version 2.0.1b using the game “Speed Racer” and the new colors seem to map the same, blue-to-lighter blue and red-to-orangish red. Are you using a particular game or program to check it? It’s easy enough to change in the code.

Jim

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BGPierce** [comment]
Hi Jim, the color sets seem to be backwards. The colors are right, but the default set should be blue. At least that's what I'm being told on the Coco Facebook group (are you a member?).
Personally, I'm a NitrOS9 user and rarely play games or use artifact colors, so I'm relying on what others tell me. I am a Coco programmer (ASM & C) but I do not know C++ or any of the PC languages well enough to do much work. I kinda had this thing thrown in my lap so I just maintain the source repository and do the release builds. I rely on others to do the coding and currently, no one has been working on it.
Oh, and thanks for the patch. There are many more needed.

Bill


-----Original Message-----

**Comment by jimrye** [comment]
Hi Bill,

I just applied to join the FB group. The colors definitely aren’t backward… All versions of VCC and the my real Coco3 agree. When you load up “Sailor Man” they all default to the blue screen. I’ll post pics in the Facebook thread once I get permissions there. I’m not a professional programmer, but I dabble in C# on the PC, so I might be able to fix a few of the issues people have posted.

Jim


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BGPierce** [comment]
Yep, we came to the same conclusion not long after I replied to you. The colors are correct.

It would be really cool if you can help with this white elephant (VCC). Most of the problems are minor but buried deep in old VS6 C++ code that was updated to VS15.
Personally, I like VCC the best of all the emulators.

Hope you like the Coco group on FB. There's a lot of well know old timers there as well as new users who just bought their first Coco on E-Bay. We have a lot of new hardware and more under development.


-----Original Message-----

**Pull request merged**
