### PR TITLE
Prevent file open dialog boxes from losing focus while open

### PR DESCRIPTION
**Pull request by Wersley**
This change is to prevent file open dialog boxes from losing focus while open.  This does not affect the main configuration dialog being modeless.

### CODE REVIEW

**Comment by BGPierce** [comment]
Done

**Comment by ursine** [comment]
I'm not seeing this reflected in master -- could it have been closed without being accepted for merge?

**Comment by BGPierce** [comment]
I thought I merged and closed, but must have hit the wrong button... good catch.

Thanks
 


Bill Pierce

**Comment by ursine** [comment]
No worries -- since I obsessively merge from upstream, noticed it was missing from the pull.

**Pull request merged**
