### PR TITLE
Vcc 1 200b

### PR DESCRIPTION
**Pull request by ursine**
This patch fixes support for the "Overclock Disk Drive" not sticking around from run to run.

### CODE REVIEW

**Comment by ursine** [comment]
Bill, I put the updated fd502.dll in the folder that I shared with you previously.

**Comment by BGPierce** [comment]
Thanks Gary, I'll check it out. Joseph is working on the WinXP thing and couple of other fixes.
 

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by vcc6809** [comment]
Got the xp thing licked also fixed the garbage when theres no disk image loaded. I also already fixed the turbo disk bug so can you send me the updated fdd source so i can pull it all together before i upload the changes.

On Oct 12, 2015, at 12:29 AM, Bill Pierce <notifications@github.com> wrote:

Thanks Gary, I'll check it out. Joseph is working on the WinXP thing and couple of other fixes.





Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull



My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com






-----Original Message-----

**Comment by BGPierce** [comment]
Joe, Gary can just merge his patch into 2.100b, then you merge yours. Once that is done, we can merge the whole thing into the Master. We now have a copy of the original upload, so the Master can represent the newest release.

Oh... did you notice my post on the keyboard bug? It's probably something simple. It seems to stay in "OS9" mode no matter what setting you use.


 BTW.. send me a set of binaries when it is all done and I will put a release package together.

 


Bill Pierce
"Charlie stole the handle, and the train it won't stop going, no way to slow down!" - Ian Anderson - Jethro Tull

 

My Music from the Tandy/Radio Shack Color Computer 2 & 3
https://sites.google.com/site/dabarnstudio/
Co-Contributor, Co-Editor for CocoPedia
http://www.cocopedia.com/wiki/index.php/Main_Page
Global Moderator for TRS-80/Tandy Color Computer Forums
http://www.tandycoco.com/forum/

E-Mail: ooogalapasooo@aol.com


 

 

-----Original Message-----

**Comment by BGPierce** [comment]
Joe, I just merged Gary's patch into the 2.100b branch. You should be able to safely merge your fixes into that branch. Once you do, build a set of binaries and send me a copy and I'll run them through the gauntlet. I'm setting up a WinXP machine right now so I can test the WinXP fix.
This thing is looking better all the time guys... Once we get all these little bugs fixed, we can start trying some new things. I definately have a wish list :-)

**Comment by BGPierce** [comment]
Gary, I just noticed, the mouse traking on full bug screen is back when I run you latest build from the Dropbox folder. Did you do something different? It was working correctly.
In a 640x192 - 2 color screen in NitrOS9, the mouse cursor (the Coco's mouse), will only move about 2/3rds of the screen both horizontally and vertically.

**Comment by ursine** [comment]
No -- only change was the dll, built the module and dropped the binary in.  The rest of the binaries are the same -- not even recompiled.

**Pull request merged**
